export const portfolioData = [
  {
    id: 1,
    name: "Le five",
    languages: ["HTML-CSS-Bootstrap"],
    languagesIcons: ["faJs", "faCss3"],
    source: "https://mohamed-a13.github.io/Evaluation-1/",
    info: "Ce projet répond à une évaluation demandé lors de ma formation chez Studi. Code source: https://github.com/mohamed-a13/Evaluation-1",
    picture: "./media/leFive.png",
  },
  {
    id: 2,
    name: "Dice Game",
    languages: ["Javascript"],
    languagesIcons: ["faJs", "faReact"],
    source: "https://mohamed-a13.github.io/Evaluation-2/",
    info: "Ce projet répond à une évaluation demandé lors de ma formation chez Studi. Code source: https://github.com/mohamed-a13/Evaluation-2",
    picture: "./media/diceGame.jpg",
  },
  {
    id: 3,
    name: "CRUD avec React et Redux",
    languages: ["React/Redux"],
    languagesIcons: ["faJs", "faPhp", "faCss3"],
    source: "https://github.com/mohamed-a13/reduxcrud",
    info: "Conception d'un CRUD avec React et Redux. (Lancer le serveur en local 'npm run server')",
    picture: "./media/crudredux.png",
  },
  {
    id: 4,
    name: "Navbar et todolist",
    languages: ["React"],
    languagesIcons: ["faJs", "faPhp", "faReact"],
    source: "https://navbar-todolist.netlify.app/",
    info: "Conception d'une barre de navigation avec une liste de tâches. Code source: https://github.com/mohamed-a13/navbar-todolist",
    picture: "./media/nav-todo.png",
  },
  {
    id: 5,
    name: "Reseau social",
    languages: ["React/NodeJs"],
    languagesIcons: ["faJs", "faCss3"],
    source: "En cours",
    info: "En cours",
    picture: "./media/travaux.jpg",
  },
  {
    id: 6,
    name: "Site E-Commerce",
    languages: ["Wordpress"],
    languagesIcons: ["faJs", "faCss3"],
    source: "En cours",
    info: "En cours",
    picture: "./media/travaux.jpg",
  },
];
